/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tec02.configuration.module.view.ItemTest.item;

import com.tec02.Jmodel.Component.MyListTabel;
import com.tec02.common.MyObjectMapper;
import com.tec02.configuration.model.itemTest.ItemTestDto;
import com.tec02.configuration.module.view.AbsTabElement;
import com.tec02.configuration.model.itemTest.ItemConfig;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class ItemPanel extends AbsTabElement<ItemTestDto> {

    private final MyListTabel<ItemConfig> modeListTabel;
    private final ShowItemConfig showItemConfig;

    /**
     * Creates new form ItemPanel
     *
     * @param tabName
     */
    public ItemPanel(String tabName) {
        super(tabName, new ItemTestDto());
        initComponents();
        this.modeListTabel = new MyListTabel(listItem);
        this.showItemConfig = new ShowItemConfig();
        this.jPanel1.add(this.showItemConfig);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        listItem = new javax.swing.JList<>();
        btAdd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtItemName = new javax.swing.JTextField();

        listItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listItemMouseClicked(evt);
            }
        });
        listItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listItemKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(listItem);

        btAdd.setText("add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        txtItemName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtItemNameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtItemName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAdd)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listItemMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            ItemConfig config = this.modeListTabel.getSelectioned();
            if (config != null) {
                this.showItemConfig.setData(config);
            }
        } else {
            this.listItem.clearSelection();
            this.showItemConfig.clear();
        }
    }//GEN-LAST:event_listItemMouseClicked

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        addItem();
    }//GEN-LAST:event_btAddActionPerformed

    private void addItem() {
        // TODO add your handling code here:
        String itemName = this.txtItemName.getText();
        if (itemName.isBlank()) {
            return;
        }
        for (ItemConfig item : this.modeListTabel.getAllItem()) {
            if (item.getItemName().equalsIgnoreCase(itemName)) {
                JOptionPane.showMessageDialog(null, String.format("%s has exists", itemName));
                return;
            }
        }
        ItemConfig config = new ItemConfig();
        config.setItemName(itemName);
        config.setTest_name(itemName);
        this.modeListTabel.addItem(config);
        this.modeListTabel.setSelected(config);
        this.txtItemName.setText(null);
    }

    private void listItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listItemKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            this.modeListTabel.removeItemSelecteds();
            this.showItemConfig.clear();
        }
    }//GEN-LAST:event_listItemKeyPressed

    private void txtItemNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addItem();
        }
    }//GEN-LAST:event_txtItemNameKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listItem;
    private javax.swing.JTextField txtItemName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refesh() {
        var items = model.getItems();
        if (items != null) {
            this.modeListTabel.removeAllItem();
            for (Map.Entry<String, ItemConfig> entry : items.entrySet()) {
                String key = entry.getKey();
                ItemConfig val = entry.getValue();
                if (key == null || val == null) {
                    continue;
                }
//                ItemConfig config = MyObjectMapper.convertValue(val, ItemConfig.class);
                val.setItemName(key);
                this.modeListTabel.addItem(val);
            }
        }
    }

    @Override
    public void update() {
        Map<String, ItemConfig> items = new HashMap<>();
        for (ItemConfig config : modeListTabel.getAllItem()) {
            items.put(config.getItemName(), config);
        }
        model.setItems(items);
    }

    @Override
    public void tabUpdate() {
    }

    @Override
    public ItemTestDto getModel() {
        return model;
    }

    @Override
    public void tabSelected() {
    }
}
