/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tec02.configuration.module.view;

import com.tec02.Jmodel.IAction;
import com.tec02.configuration.module.AbsModuleView;
import com.tec02.configuration.module.IRefeshAndUpdate;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JTabbedPane;

/**
 *
 * @author Administrator
 * @param <M> model
 * @param <V> view
 */
public abstract class AbsHasTabPanel<M, V extends AbsModuleView> extends AbsModuleView<M> implements IRefeshAndUpdate {

    private final TabPanel<V> tabPanel;
    private final HashMap<Integer, IAction<KeyEvent>> keyEvents;

    public AbsHasTabPanel(String name) {
        this(JTabbedPane.TOP, name);
    }

    public AbsHasTabPanel(int tabPlacement, String name) {
        super(name);
        initComponents();
        this.keyEvents = new HashMap<>();
        this.tabPanel = new TabPanel<>(tabPlacement);
        this.pnTab.add(tabPanel);
        this.tabPanel.setActionKeyPressed((input) -> {
            for (Map.Entry<Integer, IAction<KeyEvent>> entry : keyEvents.entrySet()) {
                if (input.getKeyCode() == entry.getKey()) {
                    entry.getValue().action(input);
                }
            }
        });
        this.keyEvents.put(KeyEvent.VK_DELETE, (input) -> {
            deleteTabSelected();
        });
    }

    public void addKeyEventAction(int keyCode, IAction<KeyEvent> event) {
        this.keyEvents.put(keyCode, event);
    }

    public void setActionKeyPressed(IAction<KeyEvent> actionKeyPressed) {
        this.tabPanel.setActionKeyPressed(actionKeyPressed);
    }

    protected void addTab(String name) {
        V modePanel = createTabPanel(name);
        modePanel.refesh();
        this.tabPanel.addTab(name, modePanel);
    }

    public int getTabSelected() {
        return this.tabPanel.getTabSelectedIndex();
    }

    @Override
    public void tabSelected() {
        getTabPanel().refesh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnTab = new javax.swing.JPanel();
        btAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtGroupName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 204, 153));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        pnTab.setBackground(new java.awt.Color(0, 204, 153));
        pnTab.setLayout(new javax.swing.BoxLayout(pnTab, javax.swing.BoxLayout.LINE_AXIS));

        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        jLabel1.setText("Tab name");

        txtGroupName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGroupNameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtGroupName, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btAdd)
                .addContainerGap())
            .addComponent(pnTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtGroupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTab, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
        );

        add(pnMain);
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        addTab();
    }//GEN-LAST:event_btAddActionPerformed

    private void txtGroupNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGroupNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addTab();
        }
    }//GEN-LAST:event_txtGroupNameKeyPressed

    public TabPanel<V> getTabPanel() {
        return tabPanel;
    }

    public void clear() {
        this.tabPanel.clearAllTab();
    }

    private void addTab() {
        String name = txtGroupName.getText();
        txtGroupName.setText(null);
        if (name.isBlank()) {
            return;
        }
        addTab(name);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JLabel jLabel1;
    protected javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnTab;
    private javax.swing.JTextField txtGroupName;
    // End of variables declaration//GEN-END:variables

    protected abstract V createTabPanel(String name);

    public String deleteTabSelected() {
        String tabDeleted = this.tabPanel.deleteTabSelected();
        deleteTabFromModel(tabDeleted);
        this.refesh();
        return tabDeleted;
    }

    protected abstract void deleteTabFromModel(String tabName);

}
