/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tec02.configuration.module.view;

import com.tec02.Jmodel.IAction;
import com.tec02.configuration.module.AbsModuleView;
import java.awt.event.KeyEvent;
import javax.swing.JTabbedPane;

/**
 *
 * @author Administrator
 * @param <M>
 * @param <V>
 */
public abstract class AbsHasTabPanel<M, V extends AbsElementTab> extends AbsModuleView<M> {

    private final TabPanel<V> tabPanel;

    public AbsHasTabPanel() {
        this(JTabbedPane.TOP);
    }

    public AbsHasTabPanel(int tabPlacement) {
        initComponents();
        this.tabPanel = new TabPanel<>(tabPlacement);
        this.pnTab.add(tabPanel);
    }

    public void setActionKeyPressed(IAction<KeyEvent> actionKeyPressed) {
        this.tabPanel.setActionKeyPressed(actionKeyPressed);
    }

    protected void addTab(String name) {
        V modePanel = createTabPanel(name);
        modePanel.refesh();
        this.tabPanel.addTab(name, modePanel);
    }

    public int getTabSelected() {
        return this.tabPanel.getTabSelectedIndex();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtGroupName = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        pnTab = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setText("Tab name");

        txtGroupName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGroupNameKeyPressed(evt);
            }
        });

        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        pnTab.setBackground(new java.awt.Color(0, 204, 153));
        pnTab.setLayout(new javax.swing.BoxLayout(pnTab, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtGroupName, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btAdd)
                .addContainerGap())
            .addComponent(pnTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtGroupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        addTab();
    }//GEN-LAST:event_btAddActionPerformed

    private void txtGroupNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGroupNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addTab();
        }
    }//GEN-LAST:event_txtGroupNameKeyPressed

    public TabPanel<V> getTabPanel() {
        return tabPanel;
    }

    public void clear() {
        this.tabPanel.clearAllTab();
    }

    private void addTab() {
        String name = txtGroupName.getText();
        txtGroupName.setText(null);
        if (name.isBlank()) {
            return;
        }
        addTab(name);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnTab;
    private javax.swing.JTextField txtGroupName;
    // End of variables declaration//GEN-END:variables

    protected abstract V createTabPanel(String name);

    public String deleteTabSelected() {
        return this.tabPanel.deleteTabSelected();
    }

}
