/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tec02.configuration.module.view;

import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JTabbedPane;

/**
 *
 * @author Administrator
 * @param <V> view
 */
public class TabPanel<V extends AbsTabElement> extends javax.swing.JPanel {

    private final Map<String, V> tabElements;

    /**
     * Creates new form TabPanel
     *
     * @param tabPlacement
     */
    public TabPanel(int tabPlacement) {
        initComponents();
        this.tabPanel.setTabPlacement(tabPlacement);
        this.tabElements = new HashMap<>();
    }

    public TabPanel() {
        this(JTabbedPane.TOP);
    }

    public void addTab(String name, V component) {
        if (name != null && !tabElements.containsKey(name)) {
            this.tabElements.put(name, component);
            this.tabPanel.add(name, component);
        }
        for (V value : tabElements.values()) {
            value.setCurremtTabPanel(this);
            value.tabUpdate();
        }
        int index = this.tabPanel.getTabCount() - 1;
        if (index >= 0) {
            this.tabPanel.setSelectedIndex(index);
        }
    }

    public V getTab(String name) {
        return tabElements.get(name);
    }

    public Map<String, V> getTabElements() {
        return tabElements;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanel = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(0, 204, 153));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        tabPanel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabPanelStateChanged(evt);
            }
        });
        tabPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabPanelKeyPressed(evt);
            }
        });
        add(tabPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void tabPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabPanelKeyPressed
        if (evt.getKeyCode() != KeyEvent.VK_DELETE) {
            return;
        }
        int index = this.tabPanel.getSelectedIndex();
        this.tabElements.remove(this.tabPanel.getTitleAt(index));
        this.tabPanel.removeTabAt(index);
        for (V value : tabElements.values()) {
            value.tabUpdate();
        }
    }//GEN-LAST:event_tabPanelKeyPressed

    public void showTab(String tabName){
        this.tabPanel.setSelectedIndex(this.tabPanel.indexOfTab(tabName));
    }
    
    private void tabPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabPanelStateChanged
        tabSelectedUpdate();
    }//GEN-LAST:event_tabPanelStateChanged

    public void tabSelectedUpdate() {
        // TODO add your handling code here:
        V tabSelected = (V) this.tabPanel.getSelectedComponent();
        if (tabSelected != null) {
            tabSelected.tabSelected();
        }
    }
    
    public void clearAllTab(){
        this.tabPanel.removeAll();
        this.tabElements.clear();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabPanel;
    // End of variables declaration//GEN-END:variables
}
