/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tec02.view.subUI.FormDetail.showGroup;

import com.tec02.Jmodel.Component.MyListTabel;
import com.tec02.configuration.model.itemTest.ItemConfig;
import com.tec02.configuration.model.itemTest.ItemGroupDto;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class ItemGroupView extends JPanel {

    private final MyListTabel<ItemConfig> listTabel;
    private final ShowGroupItem groupItem;
    private final boolean debug;

    public ItemGroupView(ShowGroupItem groupItem,
            boolean debug, ItemGroupDto groupDto,
            List<ItemConfig> itemConfigs) {
        initComponents();
        this.debug = debug;
        this.jList1.setEnabled(debug);
        this.groupItem = groupItem;
        this.listTabel = new MyListTabel(jList1, false);
        this.listTabel.addAllItem(itemConfigs);
        this.txtFailTo.setText(groupDto.getFailedTo());
        this.txtPassTo.setText(groupDto.getPassTo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        txtPassTo = new javax.swing.JTextField();
        btPassTo = new javax.swing.JButton();
        btFailTo = new javax.swing.JButton();
        txtFailTo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        btPassTo.setText("Pass to");
        btPassTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPassToActionPerformed(evt);
            }
        });

        btFailTo.setText("Fail to");
        btFailTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFailToActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(70, Short.MAX_VALUE)
                        .addComponent(btPassTo)
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassTo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFailTo)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btFailTo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPassTo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFailTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFailTo)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btPassToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPassToActionPerformed
        // TODO add your handling code here:
        String tabName = txtPassTo.getText();
        this.groupItem.settselectTab(tabName);
    }//GEN-LAST:event_btPassToActionPerformed


    private void btFailToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFailToActionPerformed
        // TODO add your handling code here:
        String tabName = txtFailTo.getText();
        this.groupItem.settselectTab(tabName);
    }//GEN-LAST:event_btFailToActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        if (debug && evt.getClickCount() > 1)
            this.groupItem.addItemToItemSelected(this.listTabel.getSelectedValuesList());
    }//GEN-LAST:event_jList1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFailTo;
    private javax.swing.JButton btPassTo;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFailTo;
    private javax.swing.JTextField txtPassTo;
    // End of variables declaration//GEN-END:variables

    public List<ItemConfig> getItemsSelected() {
        if (debug) {
            return this.listTabel.getSelectedValuesList();
        }
        return null;
    }

    public List<ItemConfig> getItems() {
        if (debug) {
            return this.listTabel.getAllItem();
        }
        return null;
    }
}
