/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tec02.view.subUI.FormDetail.showGroup;

import com.tec02.Jmodel.Component.MyListTabel;
import com.tec02.configuration.model.itemTest.ItemConfig;
import com.tec02.main.ModeManagement;
import com.tec02.main.modeFlow.ModeFlow;
import com.tec02.view.subUI.FormDetail.AbsTabUI;
import com.tec02.view.subUI.FormDetail.TabDetail;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author Administrator
 */
public class ShowGroupItem extends AbsTabUI {

    private final MyListTabel<ItemConfig> listTabel;
    private boolean isFirstTime = true;

    /**
     * Creates new form ShowGroupItem
     * @param tabDetail
     */
    public ShowGroupItem(TabDetail tabDetail) {
        super(tabDetail, "Group", -1);
        initComponents();
        this.listTabel = new MyListTabel(listITemSelected);
        this.tabGroups.removeAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabGroups = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        listITemSelected = new javax.swing.JList<>();
        btAdd = new javax.swing.JButton();
        btRemove = new javax.swing.JButton();
        btAddAll = new javax.swing.JButton();
        btRemoveAll = new javax.swing.JButton();
        btTest = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 102));

        tabGroups.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        listITemSelected.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listITemSelected);

        btAdd.setText(">");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btRemove.setText("<");
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });

        btAddAll.setText(">>");
        btAddAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddAllActionPerformed(evt);
            }
        });

        btRemoveAll.setText("<<");
        btRemoveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveAllActionPerformed(evt);
            }
        });

        btTest.setText("Test");
        btTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabGroups, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAddAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRemoveAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btTest, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabGroups, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAddAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemoveAll)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTest)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        ItemGroupView groupView = (ItemGroupView) tabGroups.getSelectedComponent();
        this.listTabel.addAllItem(groupView.getItemsSelected());
    }//GEN-LAST:event_btAddActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        // TODO add your handling code here:
        this.listTabel.removeItemSelecteds();
    }//GEN-LAST:event_btRemoveActionPerformed

    private void btAddAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddAllActionPerformed
        // TODO add your handling code here:
        ItemGroupView groupView = (ItemGroupView) tabGroups.getSelectedComponent();
        this.listTabel.addAllItem(groupView.getItems());
    }//GEN-LAST:event_btAddAllActionPerformed

    private void btRemoveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveAllActionPerformed
        // TODO add your handling code here:
        this.listTabel.removeAllItem();
    }//GEN-LAST:event_btRemoveAllActionPerformed

    private void btTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTestActionPerformed
        // TODO add your handling code here:
        this.uICell.getCellTester().runDebugItem(this.listTabel.getAllItem());
        if(tabDetail != null){
            tabDetail.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btTestActionPerformed

    @Override
    public void keyEvent(KeyEvent evt) {
    }

    @Override
    public void updateData() {
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btAddAll;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton btRemoveAll;
    private javax.swing.JButton btTest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listITemSelected;
    private javax.swing.JTabbedPane tabGroups;
    // End of variables declaration//GEN-END:variables

    @Override
    public void tabSelected(ChangeEvent evt) {
        if (isFirstTime) {
            isFirstTime = false;
            ModeFlow modeFlow = ModeManagement.getInsatace().getModeFlow();
            for (String groupName : modeFlow.getGroupNames()) {
                modeFlow.setGroup(groupName);
                this.tabGroups.addTab(groupName,
                        new ItemGroupView(this, modeFlow.getGroup(groupName).getModeRun() == 3,
                                modeFlow.getItemGroupDto(),
                                modeFlow.getListItem()));
            }
        }
    }

    public void settselectTab(String tabName) {
        for (int i = 0; i < tabGroups.getTabCount(); i++) {
            if (tabGroups.getTitleAt(i).equals(tabName)) {
                tabGroups.setSelectedIndex(i);
                return;
            }
        }
    }

    public void addItemToItemSelected(List<ItemConfig> selectedValuesList) {
        this.listTabel.addAllItem(selectedValuesList);
    }
}
