/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tec02.view;

import com.tec02.common.PcInformation;
import com.tec02.communication.DHCP.DHCP;
import com.tec02.main.Core;
import com.tec02.main.ModeManagement;
import com.tec02.view.loadModelTime.LoadModeTime;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.Timer;

/**
 *
 * @author Administrator
 */
public class Gui extends javax.swing.JFrame {

    private static volatile Gui instance;
    private final LoadModeTime modeTime;
    private final ModeManagement modeManagement;
    private final Core core;
    private final PcInformation information;

    /**
     * Creates new form Gui
     */
    private Gui() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        this.modeTime = new LoadModeTime();
        this.modeManagement = ModeManagement.getInsatace();
        this.core = Core.getInstance();
        this.information = PcInformation.getInstance();
        initComponents();
        DHCP.getgetInstance().setView(textMess);
        setIcon();
        new Timer(1000, (e) -> {
            this.lbDhcp.setBackground(DHCP.getgetInstance().isRunning() ? Color.GREEN : Color.RED);
            setTitle(String.format("%s - %s",
                    this.core.getAppName(), this.core.getSoftwareVersion()));
            if (this.information.isChanged()) {
                updatePcInfo();
            }
        }).start();
    }

    public static Gui getInstance() {
        Gui ins = Gui.instance;
        if (ins == null) {
            synchronized (Gui.class) {
                ins = Gui.instance;
                if (ins == null) {
                    Gui.instance = ins = new Gui();
                }
            }
        }
        return ins;
    }

    private void setIcon() {
        URL url = ClassLoader.getSystemClassLoader().getResource("icon.png");
        Image image = Toolkit.getDefaultToolkit().createImage(url);
        this.setIconImage(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        boardSubUI = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lbTimeVN = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textMess = new javax.swing.JTextArea();
        cbbModeTest = new javax.swing.JComboBox<>();
        lbDhcp = new javax.swing.JLabel();
        lbLine = new javax.swing.JLabel();
        lbsocket = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbNamePC = new javax.swing.JLabel();
        lbStation = new javax.swing.JLabel();
        lbIp = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtShowSfis = new javax.swing.JTextArea();
        txtInputIndex = new javax.swing.JTextField();
        txtInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelBackground.setBackground(new java.awt.Color(0, 153, 0));
        panelBackground.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelBackground.setPreferredSize(new java.awt.Dimension(1104, 768));

        boardSubUI.setBackground(new java.awt.Color(0, 153, 153));
        boardSubUI.setPreferredSize(new java.awt.Dimension(794, 700));

        javax.swing.GroupLayout boardSubUILayout = new javax.swing.GroupLayout(boardSubUI);
        boardSubUI.setLayout(boardSubUILayout);
        boardSubUILayout.setHorizontalGroup(
            boardSubUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        boardSubUILayout.setVerticalGroup(
            boardSubUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        jPanel5.setBackground(new java.awt.Color(0, 153, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbTimeVN.setBackground(new java.awt.Color(0, 153, 153));
        lbTimeVN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTimeVN.setForeground(new java.awt.Color(255, 255, 255));
        lbTimeVN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTimeVN.setText("14 : 45 : 00");
        lbTimeVN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbTimeVN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTimeVNMouseClicked(evt);
            }
        });

        textMess.setEditable(false);
        textMess.setColumns(20);
        textMess.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        textMess.setLineWrap(true);
        textMess.setRows(4);
        textMess.setWrapStyleWord(true);
        textMess.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textMess.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textMessKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(textMess);

        cbbModeTest.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N

        lbDhcp.setBackground(new java.awt.Color(204, 0, 0));
        lbDhcp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDhcp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDhcp.setText("DHCP");
        lbDhcp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbDhcp.setOpaque(true);

        lbLine.setBackground(new java.awt.Color(0, 153, 153));
        lbLine.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbLine.setForeground(new java.awt.Color(255, 255, 255));
        lbLine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLine.setText("----------");
        lbLine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbLine.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbsocket.setBackground(new java.awt.Color(204, 0, 0));
        lbsocket.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbsocket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbsocket.setText("SOCKET");
        lbsocket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbsocket.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTimeVN, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbModeTest, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLine, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbDhcp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbsocket, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLine, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbModeTest, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbDhcp)
                    .addComponent(lbsocket, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTimeVN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        this.cbbModeTest.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList jList, Object o, int i, boolean b, boolean b1) {
                JLabel rendrlbl = (JLabel) super.getListCellRendererComponent(jList, o, i, b, b1);    //todo: override
                rendrlbl.setHorizontalAlignment(SwingConstants.CENTER);
                return rendrlbl;
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 153, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbNamePC.setBackground(new java.awt.Color(0, 153, 153));
        lbNamePC.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        lbNamePC.setForeground(new java.awt.Color(255, 255, 255));
        lbNamePC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNamePC.setText("----------");
        lbNamePC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbNamePC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbStation.setBackground(new java.awt.Color(0, 153, 153));
        lbStation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbStation.setForeground(new java.awt.Color(255, 255, 255));
        lbStation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStation.setText("---");
        lbStation.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lbIp.setBackground(new java.awt.Color(0, 153, 153));
        lbIp.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lbIp.setForeground(new java.awt.Color(255, 255, 255));
        lbIp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIp.setText("---");
        lbIp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNamePC, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbStation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIp, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbStation, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbIp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNamePC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtShowSfis.setEditable(false);
        txtShowSfis.setColumns(20);
        txtShowSfis.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtShowSfis.setLineWrap(true);
        txtShowSfis.setRows(2);
        txtShowSfis.setWrapStyleWord(true);
        txtShowSfis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtShowSfisKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(txtShowSfis);

        txtInputIndex.setColumns(2);
        txtInputIndex.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtInputIndex.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInputIndex.setMaximumSize(new java.awt.Dimension(15, 33));
        txtInputIndex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInputIndexKeyPressed(evt);
            }
        });

        txtInput.setColumns(5);
        txtInput.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInput.setMaximumSize(new java.awt.Dimension(64, 33));
        txtInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInputKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInputIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInputIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boardSubUI, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boardSubUI, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbTimeVNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTimeVNMouseClicked
        // TODO add your handling code here:
        modeTime.next();
    }//GEN-LAST:event_lbTimeVNMouseClicked

    private void textMessKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMessKeyPressed
        // TODO add your handling code here:
        this.txtInput.requestFocus();
        this.txtInput.setText(String.valueOf(evt.getKeyChar()));
        showSfisText(null);
    }//GEN-LAST:event_textMessKeyPressed

    private void txtShowSfisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtShowSfisKeyPressed
        // TODO add your handling code here:
        this.txtInput.requestFocus();
        this.txtInput.setText(String.valueOf(evt.getKeyChar()));
        showSfisText(null);
    }//GEN-LAST:event_txtShowSfisKeyPressed

    private void txtInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (this.core.isMultiUICell()) {
                this.txtInputIndex.requestFocus();
            } else {
                this.core.setInput(this.txtInput.getText().trim(),
                        this.txtInputIndex.getText().trim());
                this.txtInput.setText(null);
            }
        }
        this.txtInputIndex.setText(null);
        showSfisText(null);
    }//GEN-LAST:event_txtInputKeyPressed

    public void showSfisText(String mess) {
        this.txtShowSfis.setText(mess);
    }

    public void showMess(String mess) {
        this.textMess.setText(mess);
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(null,
                "Do you want to close this program?",
                "Warning",
                JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        updatePcInfo();
        this.lbStation.setText(this.core.getStationName());
        this.lbLine.setText(this.core.getLineName());
        if (!core.isMultiUICell()) {
            this.txtInputIndex.setVisible(false);
        }
        this.txtInput.requestFocus();
        this.modeManagement.setComboBox(cbbModeTest);
        this.modeTime.setLabel(this.lbTimeVN);
        this.modeTime.setBackground(this.panelBackground);
        this.modeTime.run();
    }//GEN-LAST:event_formWindowOpened

    private void updatePcInfo() {
        // TODO add your handling code here:]
        this.lbNamePC.setText(information.getPcName());
        for (String ip : information.getIps()) {
            if (ip.startsWith("10.90.")) {
                this.lbIp.setText(ip);
                break;
            }
        }
    }

    private void txtInputIndexKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputIndexKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.core.setInput(this.txtInput.getText(),
                    this.txtInputIndex.getText());
            this.txtInput.setText(null);
            this.txtInput.requestFocus();
            this.txtInputIndex.setText(null);
        }
        showSfisText(null);
    }//GEN-LAST:event_txtInputIndexKeyPressed

    public void display() {
        java.awt.EventQueue.invokeLater(() -> {
            setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boardSubUI;
    private javax.swing.JComboBox<String> cbbModeTest;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbDhcp;
    private javax.swing.JLabel lbIp;
    private javax.swing.JLabel lbLine;
    private javax.swing.JLabel lbNamePC;
    private javax.swing.JLabel lbStation;
    private javax.swing.JLabel lbTimeVN;
    private javax.swing.JLabel lbsocket;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JTextArea textMess;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextField txtInputIndex;
    private javax.swing.JTextArea txtShowSfis;
    // End of variables declaration//GEN-END:variables

    public JPanel getDrawPanel() {
        return this.boardSubUI;
    }

    public void setSocketBackgroup(Color color) {
        this.lbsocket.setBackground(color);
    }

    public void setSocketToolTip(String tooltip) {
        this.lbsocket.setToolTipText(tooltip);
    }
}
