/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tec02.configuration.module.view.ItemTest.config;

import com.tec02.configuration.model.itemTest.ItemTestDto;
import com.tec02.configuration.model.itemTest.ModeDto;
import com.tec02.configuration.module.view.AbsHasTabPanel;
import com.tec02.configuration.module.view.AbsTabElement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JTabbedPane;

/**
 *
 * @author Administrator
 */
public class ConfigPanel extends AbsTabElement<ItemTestDto> {

    private final AbsHasTabPanel hasTabPanel;

    /**
     * Creates new form ConfigPanel
     * @param tabName
     */
    public ConfigPanel( String tabName) {
        super(tabName, new ItemTestDto());
        initComponents();
        this.hasTabPanel = new AbsHasTabPanel<ItemTestDto, ModePanel>(JTabbedPane.LEFT) {
            @Override
            protected ModePanel createTabPanel(String name) {
                ModeDto modeDto = model.getConfig().getModes().get(name);
                if (modeDto == null) {
                    modeDto = new ModeDto();
                }
                return new ModePanel(name, modeDto, model, tabPanelParent);
            }

            @Override
            public void refesh() {
                if (model == null) {
                    return;
                }
                txtLimitCmd.setText(model.getConfig().getLimit());
                var modes = model.getConfig().getModes();
                for (String name : modes.keySet()) {
                    addTab(name);
                }
            }

            @Override
            public void update() {
                Map<String, ModeDto> modes = new HashMap<>();
                model.getConfig().setModes(modes);
                for (ModePanel modePanel : getTabPanel().getTabElements().values()) {
                    modePanel.update();
                    modes.put(modePanel.getTabName(), modePanel.getModel());
                }
            }
        };
        this.jPanel1.add(this.hasTabPanel);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtLimitCmd = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 255, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Limit");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLimitCmd)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLimitCmd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    @Override
    public void refesh() {
        this.hasTabPanel.setModel(model);
        this.hasTabPanel.refesh();
    }

    @Override
    public void update() {
        this.hasTabPanel.update();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtLimitCmd;
    // End of variables declaration//GEN-END:variables

    @Override
    public void tabUpdate() {
    }

    @Override
    public ItemTestDto getModel() {
        return model;
    }

    @Override
    public void tabSelected() {
        hasTabPanel.getTabPanel().tabSelectedUpdate();
    }
}
