/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tec02.configuration.module.view.ItemTest.config;

import com.tec02.configuration.model.itemTest.ItemTestDto;
import com.tec02.configuration.model.itemTest.ModeDto;
import com.tec02.configuration.module.view.AbsTabElement;
import com.tec02.configuration.module.view.ItemTest.AbsItemTestElement;
import com.tec02.configuration.module.view.ItemTest.group.GroupPanel;
import com.tec02.configuration.module.view.TabPanel;

/**
 *
 * @author Administrator
 */
public class ModePanel extends AbsItemTestElement<ModeDto> {

    private final ItemTestDto itemTestDto;

    public ModePanel(String tabName, ModeDto modeDto, ItemTestDto itemTestDto, TabPanel<AbsTabElement> tabPanel) {
        super(tabPanel, tabName, modeDto);
        initComponents();
        this.itemTestDto = itemTestDto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtApiMode = new javax.swing.JTextField();
        spLooptest = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbbGroupName = new javax.swing.JComboBox<>();
        txtPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setText("API mode");

        spLooptest.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel2.setText("Loop test");

        jLabel3.setText("Group");

        cbbGroupName.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cbbGroupNamePopupMenuWillBecomeVisible(evt);
            }
        });

        jLabel4.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApiMode)
                    .addComponent(cbbGroupName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spLooptest, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addComponent(txtPassword))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtApiMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spLooptest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cbbGroupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbGroupNamePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbbGroupNamePopupMenuWillBecomeVisible
        updateCbbGroupName();
    }//GEN-LAST:event_cbbGroupNamePopupMenuWillBecomeVisible

    private void updateCbbGroupName() {
        // TODO add your handling code here:
        var config = this.itemTestDto.getConfig();
        var modeDto = config.getMode(tabName);
        if (modeDto == null) {
            modeDto = new ModeDto();
        }
        this.txtApiMode.setText(modeDto.getMode());
        this.spLooptest.setValue(modeDto.getLoop());
        String grName = modeDto.getGroup();
        GroupPanel groupPanel = (GroupPanel) this.tabPanelParent.getTab("Group");
        if (groupPanel != null) {
            this.cbbGroupName.removeAllItems();
            var groups = groupPanel.getTabElements().keySet();
            for (String group : groups) {
                this.cbbGroupName.addItem(group);
            }
            if (groups.contains(grName)) {
                this.cbbGroupName.setSelectedItem(grName);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbGroupName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner spLooptest;
    private javax.swing.JTextField txtApiMode;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refesh() {
        var config = this.itemTestDto.getConfig();
        var modeDto = config.getMode(tabName);
        if (modeDto == null) {
            modeDto = new ModeDto();
        }
        this.txtApiMode.setText(modeDto.getMode());
        this.txtPassword.setText(modeDto.getPassword());
        this.spLooptest.setValue(modeDto.getLoop());
        String grName = modeDto.getGroup();
        this.cbbGroupName.removeAllItems();
        var groups = this.itemTestDto.getGroups();
        for (String group : groups.keySet()) {
            this.cbbGroupName.addItem(group);
        }
        if (groups.keySet().contains(grName)) {
            this.cbbGroupName.setSelectedItem(grName);
        }
    }

    @Override
    public ModeDto getModel() {
        return model;
    }

    @Override
    public void tabUpdate() {
        updateCbbGroupName();
    }

    @Override
    public void update() {
        Object gr = cbbGroupName.getSelectedItem();
        String apiModeName = txtApiMode.getText();
//        if (gr != null) {
            model.setPassword(txtPassword.getText());
            model.setGroup(gr.toString());
            model.setLoop((Integer) spLooptest.getValue());
            model.setMode(apiModeName);
//        }
    }

    @Override
    public void tabSelected() {
        updateCbbGroupName();
    }
}
