/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * PanelTabView.java
 *
 * Created on Feb 7, 2022, 9:57:51 AM
 */
package com.tec02.view.subUI.FormDetail.TabView;

import com.tec02.function.IFunctionModel;
import com.tec02.view.subUI.FormDetail.AbsTabUI;
import java.awt.event.KeyEvent;

/**
 *
 * @author Administrator
 */
public class TabView extends AbsTabUI {

    /**
     * Creates new form PanelTabView
     *
     */
    public TabView() {
        super("View", 1000);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbStatus = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        lbStatus.setBackground(new java.awt.Color(153, 153, 255));
        lbStatus.setFont(new java.awt.Font("Arial", 1, 34)); // NOI18N
        lbStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStatus.setLabelFor(this);
        lbStatus.setText("READY");
        lbStatus.setName("lbStatus"); // NOI18N
        lbStatus.setOpaque(true);

        lbTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTime.setText("00:00");
        lbTime.setName("lbTime"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTime)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTime;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyEvent(KeyEvent evt) {
    }

    @Override
    public void endTest() {
        super.endTest(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        lbStatus.setBackground(dataCell.getResultColor());
        lbStatus.setText(String.format("<html>%s<html>",
                dataCell.getMassage().replaceAll("\r\n", "<br>")));
        lbTime.setText(getTestTime());
    }

    @Override
    public void updateData() {
        if (!this.isVisible() || !this.uICell.isTesting()) {
            return;
        }
        lbStatus.setBackground(dataCell.getTestColor());
        StringBuilder builder = new StringBuilder("<html>");
        for (IFunctionModel functionModel : dataCell.getTestingItemFunctions()) {
            builder.append(String.format("%s<br>", functionModel.getModel().getTest_name()));
        }
        builder.append("<html>");
        lbStatus.setText(builder.toString());
        lbTime.setText(getTestTime());
    }

}
