/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tec02.configuration.module.view.ItemTest;

import com.tec02.configuration.model.itemTest.ItemTestDto;
import com.tec02.configuration.module.AbsModuleView;
import com.tec02.configuration.module.view.ItemTest.config.ConfigPanel;
import com.tec02.configuration.module.view.ItemTest.group.GroupPanel;
import com.tec02.configuration.module.view.TabPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author Administrator
 */
public class ItemTestPanel extends AbsModuleView<ItemTestDto> {

    protected final TabPanel<AbsModuleView> tabPanel;

    
    public ItemTestPanel() {
        super("Items");
        initComponents();
        this.tabPanel = new TabPanel<>(JTabbedPane.LEFT);
        this.add(tabPanel);
        this.tabPanel.addTab("Config", new ConfigPanel("Config"));
        this.tabPanel.addTab("Group", new GroupPanel("Group"));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void refesh() {
        for (AbsModuleView view : this.tabPanel.getTabElements()) {
            view.setTabParentPanel(tabPanel);
            view.setModel(model);
            view.refesh();
        }
    }

    @Override
    public void update() {
        for (AbsModuleView view : this.tabPanel.getTabElements() ) {
            view.update();
        }
    }

    @Override
    public void tabSelected() {
        refesh();
    }

    @Override
    public ItemTestDto getModel() {
        return model;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
