/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tec02.configuration.module.view.ItemTest.group;

import com.tec02.Jmodel.Component.MyListTabel;
import com.tec02.configuration.model.itemTest.ItemConfig;
import com.tec02.configuration.model.itemTest.ItemGroupDto;
import com.tec02.configuration.model.itemTest.ItemTestDto;
import com.tec02.configuration.module.view.AbsTabElement;
import java.awt.Color;
import java.util.List;
import java.util.Map;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Administrator
 */
public class GroupElementPanel extends AbsTabElement<ItemGroupDto> {

    private final MyListTabel<String> modeListTabel;
    private final MyListTabel<String> applyListTabel;
    private ItemTestDto modelParent;

    public GroupElementPanel(String tabName, ItemGroupDto model) {
        super(tabName, model);
        initComponents();
        this.modeListTabel = new MyListTabel(listItems);
        this.applyListTabel = new MyListTabel(listItemSelected);
        ChangeListener changeListenerF = (ChangeEvent e) -> {
            this.pnFColor.setBackground(new Color((int) spnFr.getValue(),
                    (int) spnFg.getValue(), (int) spnFb.getValue()));
        };
        ChangeListener changeListenerT = (ChangeEvent e) -> {
            this.pnTcolor.setBackground(new Color((int) spnTr.getValue(),
                    (int) spnTg.getValue(), (int) spnTb.getValue()));
        };
        spnFr.addChangeListener(changeListenerF);
        spnFg.addChangeListener(changeListenerF);
        spnFb.addChangeListener(changeListenerF);
        spnTr.addChangeListener(changeListenerT);
        spnTg.addChangeListener(changeListenerT);
        spnTb.addChangeListener(changeListenerT);
    }

    public void setModelParent(ItemTestDto modelParent) {
        this.modelParent = modelParent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbDebug = new javax.swing.JCheckBox();
        spLooptest = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbbPassTo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbbFailTo = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listItemSelected = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listItems = new javax.swing.JList<>();
        btAdd = new javax.swing.JButton();
        btRemove = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        spnTr = new javax.swing.JSpinner();
        spnTg = new javax.swing.JSpinner();
        spnTb = new javax.swing.JSpinner();
        pnTcolor = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        spnFr = new javax.swing.JSpinner();
        spnFg = new javax.swing.JSpinner();
        spnFb = new javax.swing.JSpinner();
        pnFColor = new javax.swing.JPanel();
        spBegin = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));

        cbDebug.setText("Debug-Able");

        spLooptest.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel2.setText("Loop time");

        jLabel1.setText("Pass to");

        jLabel3.setText("Failed to");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Items"));

        jScrollPane1.setViewportView(listItemSelected);

        jScrollPane2.setViewportView(listItems);

        btAdd.setText(">>");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btRemove.setText("<<");
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btRemove, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btRemove)))
                .addContainerGap())
        );

        jLabel4.setText("Test color");

        spnTr.setModel(new javax.swing.SpinnerNumberModel(255, 0, 255, 1));

        spnTg.setModel(new javax.swing.SpinnerNumberModel(255, 0, 255, 1));

        spnTb.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));

        pnTcolor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnTcolorLayout = new javax.swing.GroupLayout(pnTcolor);
        pnTcolor.setLayout(pnTcolorLayout);
        pnTcolorLayout.setHorizontalGroup(
            pnTcolorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnTcolorLayout.setVerticalGroup(
            pnTcolorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jLabel5.setText("Fail color");

        spnFr.setModel(new javax.swing.SpinnerNumberModel(255, 0, 255, 1));

        spnFg.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));

        spnFb.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));

        pnFColor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnFColorLayout = new javax.swing.GroupLayout(pnFColor);
        pnFColor.setLayout(pnFColorLayout);
        pnFColorLayout.setHorizontalGroup(
            pnFColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnFColorLayout.setVerticalGroup(
            pnFColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        spBegin.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));

        jLabel6.setText("Begin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbDebug)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spLooptest)
                            .addComponent(cbbPassTo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbFailTo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spnTr, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spnTg, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spnTb, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pnTcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spnFr, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spnFg, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spnFb, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pnFColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 65, Short.MAX_VALUE))
                            .addComponent(spBegin))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbDebug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spLooptest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbbPassTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbFailTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnTr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnTg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnFr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnFg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnFb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnTcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnFColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        this.applyListTabel.addAllItem(this.modeListTabel.getSelectedValuesList());
    }//GEN-LAST:event_btAddActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        // TODO add your handling code here:
        this.applyListTabel.removeItemSelecteds();
    }//GEN-LAST:event_btRemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btRemove;
    private javax.swing.JCheckBox cbDebug;
    private javax.swing.JComboBox<String> cbbFailTo;
    private javax.swing.JComboBox<String> cbbPassTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listItemSelected;
    private javax.swing.JList<String> listItems;
    private javax.swing.JPanel pnFColor;
    private javax.swing.JPanel pnTcolor;
    private javax.swing.JSpinner spBegin;
    private javax.swing.JSpinner spLooptest;
    private javax.swing.JSpinner spnFb;
    private javax.swing.JSpinner spnFg;
    private javax.swing.JSpinner spnFr;
    private javax.swing.JSpinner spnTb;
    private javax.swing.JSpinner spnTg;
    private javax.swing.JSpinner spnTr;
    // End of variables declaration//GEN-END:variables

    @Override
    public synchronized void tabUpdate() {
        var tabGroups = this.tabPanelCurrent.getTabElements().keySet();
        String passSelected = (String) model.getPassTo();
        String failSelected = (String) model.getFailedTo();
        this.cbbFailTo.removeAllItems();
        this.cbbPassTo.removeAllItems();
        this.cbbFailTo.addItem("");
        this.cbbPassTo.addItem("");
        for (Object groupName : tabGroups) {
            this.cbbFailTo.addItem(groupName.toString());
            this.cbbPassTo.addItem(groupName.toString());
        }
        if (passSelected != null && !passSelected.isBlank() && tabGroups.contains(passSelected)) {
            this.cbbPassTo.setSelectedItem(passSelected);
        } else {
            this.cbbPassTo.setSelectedItem("");
        }
        if (failSelected != null && !failSelected.isBlank() && tabGroups.contains(failSelected)) {
            this.cbbFailTo.setSelectedItem(failSelected);
        } else {
            this.cbbFailTo.setSelectedItem("");
        }
    }

    @Override
    public synchronized void refesh() {
        this.cbDebug.setSelected(model.isDebug());
        this.spLooptest.setValue(model.getLoop());
        this.spBegin.setValue(model.getBegin() == null? -1: model.getBegin());
        var testColor = model.getTestColor();
        this.spnTr.setValue(testColor.get(0));
        this.spnTg.setValue(testColor.get(1));
        this.spnTb.setValue(testColor.get(2));
        this.pnTcolor.setBackground(new Color(testColor.get(0), testColor.get(1), testColor.get(2)));
        var failColor = model.getFailColor();
        this.spnFr.setValue(failColor.get(0));
        this.spnFg.setValue(failColor.get(1));
        this.spnFb.setValue(failColor.get(2));
        this.pnFColor.setBackground(new Color(failColor.get(0), failColor.get(1), failColor.get(2)));
        refeshListModel();
    }

    private synchronized void refeshListModel() {
        AbsTabElement<ItemTestDto> itemPanel = tabPanelParent.getTab("Item");
        Map<String,? extends ItemConfig> items = itemPanel.getModel().getItems();
        if ((items == null || items.isEmpty()) && modelParent != null) {
            items = modelParent.getItems();
        }
        this.applyListTabel.removeAllItem();
        this.modeListTabel.removeAllItem();
        if (items != null && !items.isEmpty()) {
            List<String> itemsInConfig = model.getItems();
            for (String itemName : itemsInConfig) {
                if (items.containsKey(itemName)) {
                    this.applyListTabel.addItem(itemName);
                }
            }
            for (String itemName : items.keySet()) {
                this.modeListTabel.addItem(itemName);
            }
        }
    }

    @Override
    public ItemGroupDto getModel() {
        return model;
    }

    @Override
    public void update() {
        model.setFailColor(List.of((int) spnFr.getValue(), (int) spnFg.getValue(), (int) spnFb.getValue()));
        model.setTestColor(List.of((int) spnTr.getValue(), (int) spnTg.getValue(), (int) spnTb.getValue()));
        model.setDebug(cbDebug.isSelected());
        var failTo = cbbFailTo.getSelectedItem();
        model.setFailedTo(failTo == null ? null : failTo.toString());
        var passTo = cbbPassTo.getSelectedItem();
        model.setPassTo(passTo == null ? null : passTo.toString());
        model.setLoop((int) spLooptest.getValue());
        model.setBegin((int) spBegin.getValue());
        model.setItems(applyListTabel.getAllItem());
    }

    @Override
    public void tabSelected() {
        refeshListModel();
    }
}
