/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tec02.configuration.module.view.ItemTest.group;

import com.tec02.configuration.model.itemTest.ItemGroupDto;
import com.tec02.configuration.model.itemTest.ItemTestDto;
import com.tec02.configuration.module.view.AbsHasTabPanel;
import com.tec02.configuration.module.view.AbsTabElement;
import com.tec02.configuration.module.view.TabPanel;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JTabbedPane;

/**
 *
 * @author Administrator
 */
public class GroupPanel extends AbsTabElement<ItemTestDto> {

    private final AbsHasTabPanel hasTabPanel;

    /**
     * Creates new form GroupPanel1
     *
     * @param tabName
     */
    public GroupPanel(String tabName) {
        super(tabName, new ItemTestDto());
        initComponents();
        hasTabPanel = new AbsHasTabPanel<ItemTestDto, GroupElementPanel>(JTabbedPane.LEFT) {
            @Override
            protected GroupElementPanel createTabPanel(String name) {
                ItemGroupDto groupDto = model.getGroups().get(name);
                if (groupDto == null) {
                    groupDto = new ItemGroupDto();
                }
                GroupElementPanel elementPanel =  new GroupElementPanel(name, groupDto);
                elementPanel.setTabPanelParent(getTabPanelParent());
                elementPanel.setModelParent(model);
                return elementPanel;
            }

            @Override
            public void refesh() {
                if (model == null) {
                    return;
                }
                var groups = model.getGroups();
                for (String name : groups.keySet()) {
                    addTab(name);
                }
            }

            @Override
            public void update() {
                Map<String, ItemGroupDto> modes = new HashMap<>();
                model.setGroups(modes);
                for (GroupElementPanel modePanel : getTabPanel().getTabElements().values()) {
                    modePanel.update();
                    modes.put(modePanel.getTabName(), modePanel.getModel());
                }
            }
        };
        this.add(this.hasTabPanel);
    }

    public TabPanel getTabPanelParent() {
        return tabPanelParent;
    }

    public AbsHasTabPanel getHasTabPanel() {
        return hasTabPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void refesh() {
        this.hasTabPanel.setModel(model);
        this.hasTabPanel.refesh();
    }

    @Override
    public void update() {
        this.hasTabPanel.update();
    }

    @Override
    public void tabUpdate() {
    }

    @Override
    public ItemTestDto getModel() {
        return model;
    }

    public TabPanel getTabPanel() {
        return hasTabPanel.getTabPanel();
    }

    public Map<String, GroupElementPanel> getTabElements() {
        return hasTabPanel.getTabPanel().getTabElements();
    }

    @Override
    public void tabSelected() {
        for (GroupElementPanel elementPanel : getTabElements().values()) {
            elementPanel.refesh();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
