/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tec02.configuration.module.view.ItemTest.group;

import com.tec02.Jmodel.Component.MyListTabel;
import com.tec02.configuration.model.itemTest.ItemConfig;
import com.tec02.configuration.model.itemTest.ItemGroupDto;
import com.tec02.configuration.model.itemTest.ItemTestDto;
import com.tec02.configuration.module.view.AbsTabElement;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JColorChooser;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Administrator
 */
public class GroupElementPanel extends AbsTabElement<ItemGroupDto> {

    private final MyListTabel<Object> modeListTabel;
    private final MyListTabel<Object> applyListTabel;
    private ItemTestDto modelParent;

    public GroupElementPanel(String tabName, ItemGroupDto model) {
        super(tabName, model);
        initComponents();
        this.modeListTabel = new MyListTabel(listItems);
        this.applyListTabel = new MyListTabel(listItemSelected);
        ChangeListener changeListenerF = (ChangeEvent e) -> {
            this.pnFColor.setBackground(new Color((int) spnFr.getValue(),
                    (int) spnFg.getValue(), (int) spnFb.getValue()));
        };
        ChangeListener changeListenerT = (ChangeEvent e) -> {
            this.pnTcolor.setBackground(new Color((int) spnTr.getValue(),
                    (int) spnTg.getValue(), (int) spnTb.getValue()));
        };
        spnFr.addChangeListener(changeListenerF);
        spnFg.addChangeListener(changeListenerF);
        spnFb.addChangeListener(changeListenerF);
        spnTr.addChangeListener(changeListenerT);
        spnTg.addChangeListener(changeListenerT);
        spnTb.addChangeListener(changeListenerT);
    }

    public void setModelParent(ItemTestDto modelParent) {
        this.modelParent = modelParent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spLooptest = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbbPassTo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbbFailTo = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listItemSelected = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listItems = new javax.swing.JList<>();
        btAdd = new javax.swing.JButton();
        btRemove = new javax.swing.JButton();
        txtItemName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spnTr = new javax.swing.JSpinner();
        spnTg = new javax.swing.JSpinner();
        spnTb = new javax.swing.JSpinner();
        pnTcolor = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        spnFr = new javax.swing.JSpinner();
        spnFg = new javax.swing.JSpinner();
        spnFb = new javax.swing.JSpinner();
        pnFColor = new javax.swing.JPanel();
        spBegin = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        slModerun = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        cbCoreGroup = new javax.swing.JCheckBox();
        btPassTo = new javax.swing.JButton();
        btFailTo = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));

        spLooptest.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel2.setText("Loop time");

        jLabel1.setText("Pass to");

        jLabel3.setText("Failed to");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Items"));

        jScrollPane1.setViewportView(listItemSelected);

        jScrollPane2.setViewportView(listItems);

        btAdd.setText(">>");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btRemove.setText("<<");
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });

        txtItemName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtItemNameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btAdd)
                            .addComponent(btRemove))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                    .addComponent(txtItemName))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(btAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btRemove)
                        .addContainerGap(33, Short.MAX_VALUE))))
        );

        jLabel4.setText("Test color");

        spnTr.setModel(new javax.swing.SpinnerNumberModel(255, 0, 255, 1));

        spnTg.setModel(new javax.swing.SpinnerNumberModel(255, 0, 255, 1));

        spnTb.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));

        pnTcolor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnTcolor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnTcolorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnTcolorLayout = new javax.swing.GroupLayout(pnTcolor);
        pnTcolor.setLayout(pnTcolorLayout);
        pnTcolorLayout.setHorizontalGroup(
            pnTcolorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnTcolorLayout.setVerticalGroup(
            pnTcolorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jLabel5.setText("Fail color");

        spnFr.setModel(new javax.swing.SpinnerNumberModel(255, 0, 255, 1));

        spnFg.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));

        spnFb.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));

        pnFColor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnFColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnFColorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnFColorLayout = new javax.swing.GroupLayout(pnFColor);
        pnFColor.setLayout(pnFColorLayout);
        pnFColorLayout.setHorizontalGroup(
            pnFColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        pnFColorLayout.setVerticalGroup(
            pnFColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        spBegin.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));

        jLabel6.setText("Begin");

        slModerun.setMaximum(3);
        slModerun.setMinimum(1);
        slModerun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Mode run");

        cbCoreGroup.setSelected(true);
        cbCoreGroup.setText("Is Core group");

        btPassTo.setText(">>");
        btPassTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPassToActionPerformed(evt);
            }
        });

        btFailTo.setText(">>");
        btFailTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFailToActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spLooptest)
                            .addComponent(spBegin)
                            .addComponent(slModerun, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spnTr, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnTg, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnTb, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnTcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spnFr, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnFg, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnFb, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnFColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbbPassTo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btPassTo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbbFailTo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btFailTo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbCoreGroup)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbCoreGroup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slModerun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spLooptest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbbPassTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPassTo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbFailTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFailTo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnTr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnTg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnFr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnFg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnFb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnTcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnFColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        this.applyListTabel.addAllItem(this.modeListTabel.getSelectedValuesList());
    }//GEN-LAST:event_btAddActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        // TODO add your handling code here:
        this.applyListTabel.removeItemSelecteds();
    }//GEN-LAST:event_btRemoveActionPerformed

    private void pnTcolorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTcolorMouseClicked
        // TODO add your handling code here:
        Color selectedColor = JColorChooser.showDialog(this, "Choose a Test-Color", this.pnTcolor.getBackground());
        if (selectedColor != null) {
            showTestColor(List.of(selectedColor.getRed(),
                    selectedColor.getGreen(),
                    selectedColor.getBlue()));
        }
    }//GEN-LAST:event_pnTcolorMouseClicked

    private void pnFColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnFColorMouseClicked
        // TODO add your handling code here:
        Color selectedColor = JColorChooser.showDialog(this, "Choose a Failed-Color", this.pnFColor.getBackground());
        if (selectedColor != null) {
            showFailColor(List.of(selectedColor.getRed(),
                    selectedColor.getGreen(),
                    selectedColor.getBlue()));
        }
    }//GEN-LAST:event_pnFColorMouseClicked

    private void btPassToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPassToActionPerformed
        // TODO add your handling code here:
        tabPanelCurrent.setSelectedTab(String.valueOf(this.cbbPassTo.getSelectedItem()));
    }//GEN-LAST:event_btPassToActionPerformed

    private void btFailToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFailToActionPerformed
        // TODO add your handling code here:
        tabPanelCurrent.setSelectedTab(String.valueOf(this.cbbFailTo.getSelectedItem()));
    }//GEN-LAST:event_btFailToActionPerformed

    private void txtItemNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String input = txtItemName.getText();
            if(input.isBlank()){
               return;
            }
            if(input.startsWith("%")){
                for (Object item : modeListTabel.getAllItem()) {
                    if(item.toString().contains(input.replaceFirst("%", ""))){
                        modeListTabel.setSelected(item);
                    }
                }
            }
        }
    }//GEN-LAST:event_txtItemNameKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btFailTo;
    private javax.swing.JButton btPassTo;
    private javax.swing.JButton btRemove;
    private javax.swing.JCheckBox cbCoreGroup;
    private javax.swing.JComboBox<String> cbbFailTo;
    private javax.swing.JComboBox<String> cbbPassTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listItemSelected;
    private javax.swing.JList<String> listItems;
    private javax.swing.JPanel pnFColor;
    private javax.swing.JPanel pnTcolor;
    private javax.swing.JSlider slModerun;
    private javax.swing.JSpinner spBegin;
    private javax.swing.JSpinner spLooptest;
    private javax.swing.JSpinner spnFb;
    private javax.swing.JSpinner spnFg;
    private javax.swing.JSpinner spnFr;
    private javax.swing.JSpinner spnTb;
    private javax.swing.JSpinner spnTg;
    private javax.swing.JSpinner spnTr;
    private javax.swing.JTextField txtItemName;
    // End of variables declaration//GEN-END:variables

    @Override
    public synchronized void tabUpdate() {
        var tabGroups = this.tabPanelCurrent.getTabElements().keySet();
        String passSelected = (String) model.getPassTo();
        String failSelected = (String) model.getFailedTo();
        this.cbbFailTo.removeAllItems();
        this.cbbPassTo.removeAllItems();
        this.cbbFailTo.addItem("");
        this.cbbPassTo.addItem("");
        for (Object groupName : tabGroups) {
            this.cbbFailTo.addItem(groupName.toString());
            this.cbbPassTo.addItem(groupName.toString());
        }
        if (passSelected != null && !passSelected.isBlank() && tabGroups.contains(passSelected)) {
            this.cbbPassTo.setSelectedItem(passSelected);
        } else {
            this.cbbPassTo.setSelectedItem("");
        }
        if (failSelected != null && !failSelected.isBlank() && tabGroups.contains(failSelected)) {
            this.cbbFailTo.setSelectedItem(failSelected);
        } else {
            this.cbbFailTo.setSelectedItem("");
        }
    }

    @Override
    public synchronized void refesh() {
        if (model == null) {
            return;
        }
        Integer begin = model.getBegin();
        this.cbCoreGroup.setSelected(model.isCoreGroup());
        this.slModerun.setValue(model.getModeRun());
        this.spLooptest.setValue(model.getLoop());
        this.spBegin.setValue(begin == null ? -1 : begin);
        showTestColor(model.getTestColor());
        showFailColor(model.getFailColor());
        refeshListModel();
    }

    private void showTestColor(List<Integer> testColor) {
        this.spnTr.setValue(testColor.get(0));
        this.spnTg.setValue(testColor.get(1));
        this.spnTb.setValue(testColor.get(2));
        this.pnTcolor.setBackground(new Color(testColor.get(0), testColor.get(1), testColor.get(2)));
    }

    private void showFailColor(List<Integer> failColor) {
        this.spnFr.setValue(failColor.get(0));
        this.spnFg.setValue(failColor.get(1));
        this.spnFb.setValue(failColor.get(2));
        this.pnFColor.setBackground(new Color(failColor.get(0), failColor.get(1), failColor.get(2)));
    }

    private synchronized void refeshListModel() {
        AbsTabElement<ItemTestDto> itemPanel = tabPanelParent.getTab("Item");
        Map<String, ? extends ItemConfig> items = itemPanel.getModel().getItems();
        if ((items == null || items.isEmpty()) && modelParent != null) {
            items = modelParent.getItems();
        }
        this.applyListTabel.removeAllItem();
        this.modeListTabel.removeAllItem();
        if (items != null && !items.isEmpty()) {
            List<String> itemsInConfig = model.getItems();
            for (String itemName : itemsInConfig) {
                if (items.containsKey(itemName)) {
                    this.applyListTabel.addItem(items.get(itemName));
                }
            }
            if (this.tabPanelCurrent != null) {
                var tabGroups = this.tabPanelCurrent.getTabElements();
                for (String item : itemsInConfig) {
                    for (Object group : tabGroups.values()) {
                        if (group.toString().equalsIgnoreCase(item)) {
                            this.applyListTabel.addItem(group);
                        }
                    }
                }
                for (Object group : tabGroups.values()) {
                    this.modeListTabel.addItem(group);
                }
            }
            for (ItemConfig item : items.values()) {
                this.modeListTabel.addItem(item);
            }
        }
    }

    @Override
    public String toString() {
        return String.format("*G-%s", getTabName());
    }

    @Override
    public ItemGroupDto getModel() {
        return model;
    }

    @Override
    public void update() {
        model.setFailColor(List.of((int) spnFr.getValue(), (int) spnFg.getValue(), (int) spnFb.getValue()));
        model.setTestColor(List.of((int) spnTr.getValue(), (int) spnTg.getValue(), (int) spnTb.getValue()));
        model.setModeRun(slModerun.getValue());
        var failTo = cbbFailTo.getSelectedItem();
        model.setFailedTo(failTo == null ? null : failTo.toString());
        var passTo = cbbPassTo.getSelectedItem();
        model.setPassTo(passTo == null ? null : passTo.toString());
        model.setLoop((int) spLooptest.getValue());
        model.setBegin((int) spBegin.getValue());
        model.setCoreGroup(cbCoreGroup.isSelected());
        List<String> items = new ArrayList<>();
        for (Object item : applyListTabel.getAllItem()) {
            items.add(item.toString());
        }
        model.setItems(items);
    }

    @Override
    public void tabSelected() {
        refeshListModel();
    }
}
