/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tec02.configuration.module.view.ItemTest.group;

import com.tec02.configuration.model.itemTest.ItemTestDto;
import com.tec02.configuration.module.view.AbsHasTabPanel;
import com.tec02.configuration.module.view.TabPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author Administrator
 */
public class GroupPanel extends AbsHasTabPanel<ItemTestDto, GroupElementPanel> {

    /**
     * Creates new form GroupPanel1
     *
     * @param tabName
     */
    public GroupPanel(String tabName) {
        super(JTabbedPane.LEFT, tabName);
        initComponents();
        this.add(pnMain);
    }

    public TabPanel getTabPanelParent() {
        return tabParentPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void refesh() {
        if (model == null) {
            return;
        }
        var groups = model.getGroups();
        clear();
        for (String name : groups.keySet()) {
            addTab(name);
        }
    }

    @Override
    public void update() {
        for (GroupElementPanel modePanel : getTabPanel().getTabElements()) {
            modePanel.update();
        }
    }

    @Override
    public ItemTestDto getModel() {
        return model;
    }

    @Override
    protected GroupElementPanel createTabPanel(String name) {
        GroupElementPanel elementPanel = new GroupElementPanel(name, model);
        elementPanel.setTabParentPanel(tabParentPanel);
        elementPanel.setTabCurremtPanel(this.getTabPanel());
        return elementPanel;
    }

    @Override
    protected void deleteTabFromModel(String tabName) {
        this.model.getGroups().remove(tabName);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
