/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tec02.configuration.module.view.ItemTest.group;

import com.tec02.Jmodel.Component.MyListTabel;
import com.tec02.configuration.model.itemTest.ItemConfig;
import javax.swing.Timer;

/**
 *
 * @author Administrator
 */
class SearchItem extends javax.swing.JFrame {

    private final MyListTabel<Object> modeListTabel;
    private final MyListTabel<Object> rootModeListTabel;
    private final MyListTabel<Object> rootApplyListTabel;
    private final ShowConfig showConfig;
    private final Timer timer;
    private String oldString;

    /**
     * Creates new form SearchItem1
     */
    SearchItem(MyListTabel<Object> modeListTabel, MyListTabel<Object> applyListTabel, ShowConfig showConfig) {
        initComponents();
        this.modeListTabel = new MyListTabel(listItems);
        this.showConfig = showConfig;
        this.rootModeListTabel = modeListTabel;
        this.rootApplyListTabel = applyListTabel;
        this.modeListTabel.setDoubleClickAction((input) -> {
            showItemSelected(this.modeListTabel.getSelectioned());
        });
        this.timer = new Timer(500, (e) -> {
            String searchString = txtSearch.getText().trim();
            String itemName;
            if (searchString != null && !searchString.equals(oldString)) {
                System.out.println(searchString);
                oldString = searchString;
                this.modeListTabel.removeAllItem();
                if (searchString.isBlank()) {
                    this.modeListTabel.addAllItem(this.rootModeListTabel.getAllItem());
                }
                for (Object itemOb : this.rootModeListTabel.getAllItem()) {
                    if (itemOb == null) {
                        continue;
                    }
                    itemName = itemOb.toString().trim().toLowerCase();
                    if (itemName.contains(searchString.toLowerCase())) {
                        this.modeListTabel.addItem(itemOb);
                    }
                }
            }
        });
    }

    private void showItemSelected(Object objectSelected) {
        if (objectSelected instanceof ItemConfig itemConfig) {
            showConfig.display(itemConfig);
        }
    }

    void display() {
        java.awt.EventQueue.invokeLater(() -> {
            this.modeListTabel.removeAllItem();
            this.modeListTabel.addAllItem(rootModeListTabel.getAllItem());
            this.timer.start();
            setVisible(true);
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listItems = new javax.swing.JList<>();
        txtSearch = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Items"));

        jScrollPane2.setViewportView(listItems);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );

        btAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btAdd)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAdd)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        this.rootApplyListTabel.addAllItem(this.modeListTabel.getSelectedValuesList());
    }//GEN-LAST:event_btAddActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.timer.stop();
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listItems;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

}
