/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tec02.configuration.module.view.ItemTest.group;

import com.tec02.configuration.model.itemTest.ItemConfig;
import com.tec02.configuration.module.view.ItemTest.item.ShowItemConfig;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Administrator
 */
public class ShowConfig extends javax.swing.JFrame {

    private final ShowItemConfig showConfig;
    private final Timer timer;

    /**
     * Creates new form ShowItemConfig
     */
    public ShowConfig() {
        initComponents();
        this.showConfig = new ShowItemConfig();
        this.pnShowConfig.add(showConfig);
        this.timer = new Timer(500, (e) -> {
            String itemName = this.showConfig.getItemName();
            if(itemName == null){
                return;
            }
            if (!this.showConfig.isSaved()) {
                this.setTitle("*" + itemName);
            }else{
                this.setTitle(itemName);
            }
        });
        this.timer.start();
    }

    public JPanel getPnShowConfig() {
        return pnShowConfig;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnShowConfig = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnShowConfig.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnShowConfig, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnShowConfig, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        askAndSave();
    }//GEN-LAST:event_formWindowClosing

    public void askAndSave() throws HeadlessException {
        // TODO add your handling code here:
        if (!showConfig.isSaved() && showConfig.getConfig() != null && JOptionPane.showConfirmDialog(null,
                "Bạn có muốn lưu lại tất cả thay dổi không?",
                "Warning", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            showConfig.save();
        }
    }

    public void setData(ItemConfig itemConfig) {
        showConfig.setData(itemConfig);
        setTitle(itemConfig.toString());
    }

    public void display(ItemConfig itemConfig) {
        setData(itemConfig);
        java.awt.EventQueue.invokeLater(() -> {
            ShowConfig.this.setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnShowConfig;
    // End of variables declaration//GEN-END:variables

}
