/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * TagLog.java
 *
 * Created on Feb 7, 2022, 6:28:13 PM
 */
package com.tec02.view.subUI.FormDetail.TabItem;

import com.tec02.Jmodel.Component.MyTable;
import com.tec02.function.IFunctionModel;
import com.tec02.view.subUI.FormDetail.AbsTabUI;
import com.tec02.view.subUI.FormDetail.TabItem.ShowLog.ShowLog;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class TabItem extends AbsTabUI {

    private static final String STATUS_COULMN = "Status";
    private static final String TIME_COULMN = "Time";
    private static final String ITEM_COULMN = "Item";
    private static final String STT_COULMN = "STT";
    private static final String ERROR_CODE_COULMN = "Error code";
    private static final String CUS_ERROR_CODE_COULMN = "Cus error code";
    private final Map<String, ShowLog> itemLogs;
    private final MyTable myTable;
    private final List<Boolean> itemFinish;

    /**
     * Creates new form TagLog
     *
     */
    public TabItem() {
        super("Item", 1000);
        initComponents();
        this.itemFinish = new ArrayList<>();
        this.itemLogs = new HashMap<>();
        this.myTable = new MyTable(tableItem);
    }

    private void showItemLogSelected() {
        String functionName = this.myTable.getRowSelectedValue(name);
        IFunctionModel dataBox = this.dataCell.getFunction(functionName);
        if (dataBox == null) {
            return;
        }
        if (itemLogs.containsKey(functionName)) {
            itemLogs.get(functionName).showLog();
        } else {
            ShowLog itemLog = new ShowLog(dataBox, uICell);
            itemLog.showLog();
            itemLogs.put(functionName, itemLog);
        }
    }

    private void initTable() {
        this.myTable.initTable(List.of(STT_COULMN,
                ITEM_COULMN, TIME_COULMN,
                STATUS_COULMN, CUS_ERROR_CODE_COULMN, ERROR_CODE_COULMN));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableItem = new javax.swing.JTable();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tableItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableItem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tableItem.setModel(new javax.swing.table.DefaultTableModel(
            null,
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableItem.setName("tableItem"); // NOI18N
        tableItem.setRowHeight(30);
        tableItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableItemMouseClicked(evt);
            }
        });
        tableItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keyEvent(evt);
            }
        });
        jScrollPane1.setViewportView(tableItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableItemMouseClicked
        if (evt.getClickCount() > 1) {
            showItemLogSelected();
        }
    }//GEN-LAST:event_tableItemMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableItem;
    // End of variables declaration//GEN-END:variables

    private static final int CTRL_S = 19;
    private static final int CTRL_D = 4;
    private static final int CTRL_Q = 17;

    @Override
    public void startTest() {
        for (ShowLog itemLog : itemLogs.values()) {
            itemLog.dispose();
        }
        this.itemLogs.clear();
        this.itemFinish.clear();
        initTable();
        super.startTest();
    }

    @Override
    public void updateData() {
        if (!this.isVisible()) {
            return;
        }
        try {
            IFunctionModel dataBox;
            for (int row = 0; row < functionModels.size(); row++) {
                if (isHasFinish(row)) {
                    continue;
                }
                dataBox = functionModels.get(row);
                if (row > this.myTable.getRowCount() - 1) {
                    this.myTable.addRow(new Object[]{this.myTable.getRowCount()});
                    this.itemFinish.add(false);
                    showDataTest(dataBox, row);
                } else {
                    showDataTest(dataBox, row);
                }
                if (dataBox.isDone()) {
                    this.itemFinish.set(row, true);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void showDataTest(IFunctionModel dataBox, int row) {
        var model = dataBox.getModel();
        this.myTable.setValueAt(row, ITEM_COULMN, model.getTest_name());
        this.myTable.setValueAt(row, TIME_COULMN, String.format("%.3f S", dataBox.getRunTime()/1000.0));
        this.myTable.setValueAt(row, STATUS_COULMN, getStatus(dataBox));
        this.myTable.setValueAt(row, ERROR_CODE_COULMN, model.getErrorcode());
        this.myTable.setValueAt(row, CUS_ERROR_CODE_COULMN, model.getError_code());
    }

    private boolean isHasFinish(int row) {
        return row < this.itemFinish.size() && this.itemFinish.get(row);
    }

    private boolean isAccepToStopTest() {
        return JOptionPane.showConfirmDialog(null,
                "Chọn \"Yes\" để dừng test", "Messager",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION;
    }

    @Override
    public void keyEvent(KeyEvent evt) {
        if(evt.getKeyChar() == CTRL_Q){
            if(isAccepToStopTest()){
               this.uICell.getCellTester().stop();
            }
        }
    }

    private String getStatus(IFunctionModel dataBox) {
        if(dataBox.isWaiting()){
            return "Waiting";
        }else if(dataBox.isTesting()){
            return "Testing";
        }else{
            return dataBox.getModel().getStatus();
        }
    }
}
