/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tec02.view.subUI.SubUI.BigUI;

import com.tec02.view.subUI.SubUI.AbsSubUI;
import java.awt.Color;

/**
 *
 * @author Administrator
 */
public class BigUI extends AbsSubUI {

    protected boolean debugMode;

    /**
     * Creates new form BigUI
     *
     * @param indexName
     */
    public BigUI(String indexName) {
        super(indexName, 500);
        initComponents();
        this.add(this.tabDetail);
    }

    @Override
    public void startTest() {
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void setText(String txt) {
    }

    @Override
    public void updateData() {
        
    }

    @Override
    protected void showEnd(Color color, boolean status) {
    }

   

}
