/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tec02.configuration.module;

import com.tec02.configuration.controller.ConfigurationManagement;
import com.tec02.configuration.module.view.TabPanel;

/**
 *
 * @author Administrator
 */
public class TabConfiguramentPanel extends javax.swing.JPanel {

    private final ConfigurationManagement management;
    private final TabPanel<AbsModuleView> tabPanel;

    /**
     * Creates new form TabPanel
     *
     * @param management
     */
    public TabConfiguramentPanel(ConfigurationManagement management) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        initComponents();
        this.management = management;
        this.tabPanel = new TabPanel();
        this.tabPanel.setShowNewTab(false);
        this.jPanel1.add(this.tabPanel);
    }

    public final void refesh() {
        this.management.refesh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btRefesh = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btReload = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 255));

        btRefesh.setBackground(new java.awt.Color(0, 153, 102));
        btRefesh.setText("Refesh");
        btRefesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefeshActionPerformed(evt);
            }
        });

        btUpdate.setBackground(new java.awt.Color(0, 204, 204));
        btUpdate.setText("Update");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        btReload.setBackground(new java.awt.Color(102, 102, 255));
        btReload.setText("Reload");
        btReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btReload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRefesh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btUpdate)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRefesh)
                    .addComponent(btUpdate)
                    .addComponent(btReload))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        // TODO add your handling code here:
        this.management.update();
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReloadActionPerformed
        // TODO add your handling code here:
        reload();
    }//GEN-LAST:event_btReloadActionPerformed

    private void btRefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefeshActionPerformed
        // TODO add your handling code here:
        refesh();
    }//GEN-LAST:event_btRefeshActionPerformed

    public final void reload() {
        this.management.init();
        if (this.tabPanel.isEmpty()) {
            this.tabPanel.clearAllTab();
            var modules = this.management.getModules();
            for (AbsModule module : modules) {
                this.tabPanel.addTab(module.getName(), module.getView());
            }
        }
        refesh();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRefesh;
    private javax.swing.JButton btReload;
    private javax.swing.JButton btUpdate;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
