/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * Detail.java
 *
 * Created on Nov 30, 2021, 9:54:11 AM
 */
package com.tec02.view.subUI.FormDetail;




/**
 *
 * @author Administrator
 */
public class FormShow extends javax.swing.JFrame {

    private final TabDetail tabDetail;
    /**
     * Creates new form Detail
     *
     * @param tabDetail
     */
    public FormShow(TabDetail tabDetail) {
        initComponents();
        this.add(tabDetail);
        this.tabDetail = tabDetail;
    }

    
    public void display(String title){
        this.setTitle(title);
        this.setVisible(true);
        this.tabDetail.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        setSize(new java.awt.Dimension(753, 475));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
